In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('heart_failure.csv')
df.head()

    age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
0  75.0        0                       582  ...        0     4            1
1  55.0        0                      7861  ...        0     6            1
2  65.0        0                       146  ...        1     7            1
3  50.0        1                       111  ...        0     7            1
4  65.0        1                       160  ...        0     8            1

[5 rows x 13 columns]

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    int64
dtypes: float64(3), int64(10)
memory usage: 30.5 KB

In [7]:
df.describe().T

                          count           mean  ...       75%       max
age                       299.0      60.833893  ...      70.0      95.0
anaemia                   299.0       0.431438  ...       1.0       1.0
creatinine_phosphokinase  299.0     581.839465  ...     582.0    7861.0
diabetes                  299.0       0.418060  ...       1.0       1.0
ejection_fraction         299.0      38.083612  ...      45.0      80.0
high_blood_pressure       299.0       0.351171  ...       1.0       1.0
platelets                 299.0  263358.029264  ...  303500.0  850000.0
serum_creatinine          299.0       1.393880  ...       1.4       9.4
serum_sodium              299.0     136.625418  ...     140.0     148.0
sex                       299.0       0.648829  ...       1.0       1.0
smoking                   299.0       0.321070  ...       1.0       1.0
time                      299.0     130.260870  ...     203.0     285.0
DEATH_EVENT               299.0       0.321070  ...       1.0       1.0

[13 rows x 8 columns]

In [8]:
df.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
x = df.drop('DEATH_EVENT', axis=1)
y = df['DEATH_EVENT']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [12]:
x_train

        age  anaemia  creatinine_phosphokinase  ...  sex  smoking  time
6    75.000        1                       246  ...    1        0    10
183  75.000        0                        99  ...    1        0   162
185  60.667        1                       104  ...    1        0   171
146  52.000        0                       132  ...    1        1   112
30   94.000        0                       582  ...    1        0    27
..      ...      ...                       ...  ...  ...      ...   ...
188  60.667        1                       151  ...    0        0   172
71   58.000        0                       582  ...    1        1    71
106  55.000        0                       748  ...    1        0    88
270  44.000        0                       582  ...    1        1   244
102  80.000        0                       898  ...    1        1    87

[239 rows x 12 columns]

In [13]:
y_train

6      1
183    1
185    1
146    0
30     1
      ..
188    0
71     0
106    0
270    0
102    0
Name: DEATH_EVENT, Length: 239, dtype: int64

In [14]:
x_test

      age  anaemia  creatinine_phosphokinase  ...  sex  smoking  time
281  70.0        0                       582  ...    1        1   250
265  50.0        1                       298  ...    1        1   240
164  45.0        0                      2442  ...    1        0   129
9    80.0        1                       123  ...    1        1    10
77   42.0        0                       102  ...    1        0    74
278  50.0        1                      1051  ...    0        0   246
93   60.0        1                       154  ...    1        0    82
109  45.0        0                       292  ...    1        1    88
5    90.0        1                        47  ...    1        1     8
173  50.0        1                       115  ...    1        0   146
97   70.0        1                        59  ...    0        0    85
195  77.0        1                       418  ...    1        0   180
184  58.0        1                       145  ...    1        1   170
154  65.0        1                       335  ...    0        0   120
57   60.0        1                       607  ...    1        1    54
60   45.0        0                      7702  ...    1        0    60
147  64.0        0                      1610  ...    1        0   113
108  63.0        0                       936  ...    1        1    88
63   45.0        0                       582  ...    1        0    61
140  80.0        0                       805  ...    1        0   109
155  60.0        1                       231  ...    1        0   120
104  60.0        0                        53  ...    0        0    87
247  64.0        0                       143  ...    1        0   214
46   51.0        0                      1380  ...    1        0    38
42   70.0        0                       571  ...    1        1    33
275  45.0        0                       582  ...    0        0   245
280  70.0        0                      2695  ...    1        0   247
116  60.0        1                        96  ...    0        0    94
213  48.0        1                       131  ...    0        0   193
236  75.0        0                       119  ...    1        0   209
17   45.0        0                       582  ...    1        0    14
239  55.0        1                       180  ...    1        1   211
33   50.0        1                       159  ...    0        0    29
24   75.0        0                       582  ...    0        0    23
45   50.0        0                       582  ...    1        1    35
7    60.0        1                       315  ...    1        1    10
113  70.0        1                       143  ...    0        0    90
194  45.0        0                       582  ...    1        0   180
111  55.0        0                        60  ...    1        1    90
92   42.0        0                       582  ...    0        0    82
75   60.0        1                        47  ...    1        1    73
82   60.0        1                        76  ...    0        0    77
118  65.0        1                       113  ...    0        0    94
76   70.0        0                        92  ...    0        1    74
129  53.0        1                       270  ...    1        0   105
197  65.0        0                       167  ...    0        0   186
210  70.0        0                       212  ...    1        1   188
288  65.0        0                       892  ...    0        0   256
219  55.0        0                       582  ...    0        0   197
178  63.0        1                       122  ...    1        0   147
144  72.0        1                       943  ...    1        1   111
186  50.0        0                       582  ...    0        0   172
84   59.0        1                       280  ...    0        0    78
248  40.0        0                       624  ...    1        1   214
277  70.0        0                       582  ...    1        0   246
73   65.0        0                       224  ...    1        1    72
244  54.0        0                       582  ...    1        0   213
25   80.0        0                       148  ...    1        1    23
209  49.0        0                       972  ...    0        0   187
59   72.0        0                       364  ...    1        1    59

[60 rows x 12 columns]

In [17]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [18]:
model = LogisticRegression()
model.fit(x_train_scaled, y_train)
y_pred = model.predict(x_test_scaled)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.97      0.85        35
           1       0.93      0.56      0.70        25

    accuracy                           0.80        60
   macro avg       0.84      0.77      0.77        60
weighted avg       0.83      0.80      0.79        60

In [19]:
import joblib
joblib.dump(model, 'heart_failure_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']